### ISSUE TITLE
Nice, although demo doesn't function

### ISSUE THREAD

**Issue by appsolutegeek** [SumiMakito/Awesome-qr.js#1]
Had a quick look at the demo and I can see a base64 image coming back in chrome dev tools but the UI isn't updated when you click the generate button.

Out of interest, is it injecting a canvas ? or just an img? 

Do you know if this is compatible with old/new browsers?

Thanks in advance.

Great start!

**Comment by SumiMakito** [comment]
Thanks for the feedback. :)

Yesterday I forgot to update the demo web page after the .js file had been updated to version 1.0.3.
I've updated the demo web page at 21:50(+08:00) on May 5, but I guess CDN may hold the previously cached version of index.html, you can try to clear your browser's cache to get the latest page. 

> Out of interest, is it injecting a canvas ? or just an img?

Awesome-qr.js finally returns a data URI. After version 1.0.3, it can inject the data URI into the element automatically, if specified. 
For `<img>` elements, awesome-qr will try to assign the data URI to its `src` attribute. And for `<div>` or others, awesome-qr will try to set the data URI as `background-image` of the given element. 

> Do you know if this is compatible with old/new browsers?

I've just updated the readme, in which I added a compatibility list.
[Explore the compatibility list](https://github.com/SumiMakito/Awesome-qr.js/blob/master/README.md#compatibility-兼容性) 

Cheers
