### ISSUE TITLE
1.1版的包运行报错

### ISSUE THREAD

**Issue by dongnaebi** [SumiMakito/Awesome-qr.js#11]
npm安装一直不成功，所以用的cnpm安装，是能安装成功，但一运行就报错，can't resolve ‘awesome-qr’，引用方式是import，v1.0.9是没问题的

**Comment by LIU9293** [comment]
Hello, I love this project a lot but found the same problem, so I created a new repository, improved the bundle process and made some refactors. You can find it [here](https://github.com/LIU9293/art-qr) if you like.

**Comment by SumiMakito** [comment]
你好，如需在 Node 服务器上使用，请使用 V1.2.0 及更高版本。
若仅在浏览器中（非后端）使用，推荐按照文档直接引入 JavaScript 文件。
V1.0.9 及 V1.1.0 版本的 package.json 缺少必要依赖。
