### ISSUE TITLE
建议新增码点和码眼设置参数

### ISSUE THREAD

**Issue by yumufeng** [SumiMakito/Awesome-qr.js#12]
码点设置：
1.默认是正方形点
2.建议增加“圆形” 点  canvas.arc(x+(w/2),y+(h/2),w/2,0,2*Math.PI)
3.建议增加“菱形”点，可以更自由设置点

码眼:
既然要与众不同，那码眼也可以设置，目前思路是用图片定位覆盖。

**Comment by SumiMakito** [comment]
感谢建议，数据区的圆点已在计划中，因面向 Android 的同名二维码库已具备此功能。Position detection patterns 如需自定义还需考虑 QRCode 的可识别性的问题。

**Comment by yumufeng** [comment]
![qrcode](https://user-images.githubusercontent.com/9146937/33928458-f2f3dd7e-e020-11e7-9aaa-1e76b7830c88.jpg)

在QRcode 的 Position detection patterns 点周围都加上白色隔离带，能有效提升解码效率。

如果用Python或者Java版本话，可以考虑加入Face++ 或者OpenCV之类功能，采用“半监督式学习”能有效提升编码率。

**Comment by SumiMakito** [comment]
半透明白色的 Protectors 其实已存在，调整覆盖范围即可。OpenCV 有过开发经验，不过不是很清楚二者结合的必要性。

**Comment by yumufeng** [comment]
可应用的区域广泛的很啊，人脸识别不就是一个，商务名片上，B格就高不少。中国印刷每年几十亿的市场。。其他的慢慢发现。。
