### ISSUE TITLE
npm install装不上

### ISSUE THREAD

**Issue by Coder-JJ** [SumiMakito/Awesome-qr.js#13]
Win 10
node v8.9.3

提示python node-gyp blablabla，装了node-gyp之后报错又变了

![image](https://user-images.githubusercontent.com/34091965/34236083-aefcfb4e-e630-11e7-83d8-752cb670a5ed.png)

![image](https://user-images.githubusercontent.com/34091965/34236174-1ab0544e-e631-11e7-8c16-f5ad23f07bbe.png)

**Comment by SumiMakito** [comment]
![2017-12-21 12 25 35](https://user-images.githubusercontent.com/5277268/34240583-44b32230-e64a-11e7-9b26-d36c5c880bc6.png)
你好，这个应该是由依赖项 node-canvas 在 Windows 下出现的问题。
可参考 node-canvas 的一些 Issues，也有报告类似问题。
https://github.com/Automattic/node-canvas/issues/619
https://github.com/Automattic/node-canvas/issues/884

**Comment by Coder-JJ** [comment]
弄了一天还是不行，退回老版本了

**Comment by SumiMakito** [comment]
已在 Readme 中更新，node-canvas 这个依赖需要预先配置，否则可能会产生问题。
也可参考其安装说明 https://github.com/Automattic/node-canvas#installation 。
