### ISSUE TITLE
关于code length overflow. (1684>1056)

### ISSUE THREAD

**Issue by 35860368** [SumiMakito/Awesome-qr.js#14]
在text的内容url地址而且长度过长的时候会出现标题中的错误信息，请问有办法解决此列问题吗

**Comment by SumiMakito** [comment]
你好，使用 Node 版和浏览器适用的版本测试长达 2150 字符的字符串暂未发现问题。
可以提供一下欲编码的 URL 长度为多少字符以及使用的版本吗？

**Comment by 35860368** [comment]
node 版本8.4.0，vue-qr版本1.2.3,下图未报错的信息，和打印的报错的url
![tim 20171222162618](https://user-images.githubusercontent.com/6647514/34290951-e5c3411a-e734-11e7-822f-5376e1aac148.png)
![tim 20171222162625](https://user-images.githubusercontent.com/6647514/34290953-e744132a-e734-11e7-87f0-177c5a55f5b4.png)

**Comment by 35860368** [comment]
这个的url截图打开后实际的内容：
http://400423541.scene.eqxiu.com/s/EqeBwrNY?share_level=2&amp;from_user=93699658-93d2-4a57-934e-549ce46026e2&amp;from_id=ebff1a98-1750-4bca-88fd-d6682c339b79&amp;share_time=1513828514342&amp;from=groupmessage

**Comment by SumiMakito** [comment]
长度溢出的问题应该已经修复过了，尝试用 `npm remove vue-qr; npm install vue-qr` 来更新一下它的依赖，这个 Vue-qr 很有可能是在问题被修复之前安装的。

**Comment by 35860368** [comment]
好的，谢谢。

**Comment by SumiMakito** [comment]
可以参考一下 node-canvas 给出的 Windows 依赖安装指南 https://github.com/Automattic/node-canvas/wiki/Installation---Windows 。
