### ISSUE TITLE
增加中间 logo 的建议

### ISSUE THREAD

**Issue by Binaryify** [SumiMakito/Awesome-qr.js#2]
理论上只要二维码纠错率足够高,中间加个 logo 还是能识别出来的,我自己也试验过,生成的二维码在中间 p 上 logo还是能正常识别的,希望能加入中间 logo 的功能

**Comment by SumiMakito** [comment]
这个有计划的，近期加上。

**Comment by Binaryify** [comment]
另外希望能把代码结构整理成 umd 格式的，目前的代码格式无法在 webpack 里 require

**Comment by SumiMakito** [comment]
嗯。

**Comment by SumiMakito** [comment]
New feature added in 22e9b38b46ee9e48d786a5083328403a2f3e072b. :)
