### ISSUE TITLE
size 小于800  logo 位置不正确

### ISSUE THREAD

**Issue by Binaryify** [SumiMakito/Awesome-qr.js#4]
![image](https://cloud.githubusercontent.com/assets/12221718/25848078/58316544-34eb-11e7-825a-0194daa3030d.png)
另外有个 logoImg 未定义

**Comment by SumiMakito** [comment]
Issue fixed in cb90ccfaf64da7c0c171fd0a9f88c6e929beeee4 and 97f51b6995fb0014ae45f65f6da6eca8b5ccb55c.

**Comment by Binaryify** [comment]
@SumiMakito 
Logo 位置问题还没修复

**Comment by SumiMakito** [comment]
在用演示网页测试吗？

**Comment by Binaryify** [comment]
@SumiMakito 
本地和 demo 网页都试过了

**Comment by SumiMakito** [comment]
![2017-05-09 19 43 30](https://cloud.githubusercontent.com/assets/5277268/25849143/db35812e-34ef-11e7-93d7-e104e3bf3d9b.png)
演示网页刚刚更新

**Comment by Binaryify** [comment]
ok 了
