### ISSUE TITLE
logo加载不出来

### ISSUE THREAD

**Issue by VoliBearCat** [SumiMakito/Awesome-qr.js#8]
`````           
            var avatar = new Image()
            avatar.src = this.imageURL
            new AwesomeQRCode().create({
              text: '这是怎么肥事???',
              size: 380,
              margin: 20,
              dotScale: 1,
              backgroundImage: undefined,
              logoImage: avatar,
              logoScale: .2,
              logoMargin: 4,
              autoColor: true,
              logoCornerRadius: 0,
              callback: function (dataURI) {
                // console.log(dataURI);
              },
              bindElement: 'qrcode'
            });
`````
![3ry j osln 9vkd x jd](https://user-images.githubusercontent.com/11676384/28965122-2d41f6a0-7942-11e7-8dbd-3dc1874c03d4.png)
![rw b3xxq ha4u3 43nad](https://user-images.githubusercontent.com/11676384/28965123-2d4aa61a-7942-11e7-807a-f58ababe97b3.png)

**Comment by Blockis** [comment]
Seeing the same issue on my end.

**Comment by SumiMakito** [comment]
```Image``` in JavaScript will load the image from the given ```src``` asynchronously, so you need to know when the image has finished loading by adding a callback.

```javascript
var img = new Image();
img.onload = function() {
    // Use the img
};
img.src = "Some URL";
```
You can also take a look at: https://jsfiddle.net/sumimakito/45L3okhe/1/

**Comment by VoliBearCat** [comment]
Thank you, I get it.

**Comment by VoliBearCat** [comment]
I've tried onload function, but it still doesn't work. 
The point is to set "crossorigin = 'anonymous'", find it from your demo.

**Comment by SumiMakito** [comment]
That's right. Without setting the "crossOrigin" property, canvas will suffer security issues while loading images from external resources. 
For more information, you can refer to this article: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
Cheers
